CREATE TABLE post (
	id SERIAL,
	html VARCHAR(1024) NOT NULL,
	posted TIMESTAMP WITH TIME ZONE NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT NOW(),
	deleted TIMESTAMP DEFAULT NULL
);

CREATE TABLE follower (
);

CREATE TABLE follow (
);
