CREATE TABLE post (
	id SERIAL,
	html VARCHAR(1024) NOT NULL,
	posted TIMESTAMP WITH TIME ZONE NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT NOW(),
	deleted TIMESTAMP
);

CREATE TABLE rsscloud (
	id SERIAL,
	url VARCHAR(1024) UNIQUE NOT NULL,
	method VARCHAR(100) NOT NULL,
	subscribedUntil TIMESTAMP NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT NOW()
);
