CREATE TABLE schema (
	version INTEGER UNIQUE NOT NULL,
	upgraded TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE account (
	id SERIAL PRIMARY KEY,
	name VARCHAR(30) UNIQUE NOT NULL,
	passwordHash VARCHAR(60) NOT NULL,
	displayName CHARACTER VARYING NOT NULL
);

CREATE TABLE author (
	id SERIAL PRIMARY KEY,
	name CHARACTER VARYING NOT NULL,
	url VARCHAR(1024) UNIQUE NOT NULL
);

CREATE TABLE post (
	id SERIAL PRIMARY KEY,
	authorid INTEGER NOT NULL REFERENCES author(id),
	url VARCHAR(1024),
	html CHARACTER VARYING NOT NULL,
	posted TIMESTAMP WITH TIME ZONE NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT NOW(),
	deleted TIMESTAMP
);

CREATE TABLE writestream (
	id SERIAL PRIMARY KEY,
	postid INTEGER NOT NULL REFERENCES post(id),
	posted TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE rsscloud (
	id SERIAL,
	url VARCHAR(1024) UNIQUE NOT NULL,
	method VARCHAR(100) NOT NULL,
	subscribedUntil TIMESTAMP NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE import (
	id SERIAL,
	value INTEGER NOT NULL,
	source CHARACTER VARYING NOT NULL,
	identifier CHARACTER VARYING NOT NULL,
	UNIQUE(source, identifier)
);
